---
# tasks file for tomcat-test
- name: Check if Tomcat Responds 200
  shell: curl -sL -w "%{http_code}" localhost:8080 -o /dev/null | grep 200
  register: tomcat_output
  args:
   warn: false

- name: Printing Respond Code
  debug: msg="{{ tomcat_output.stdout }}" 
